#!/bin/bash

cd $PREFIX/bin
rm -Rf said-update said act
cd $PREFIX/lib
rm -Rf config-base
cd $PREFIX/libexec
rm -Rf acot
cd
rm -Rf SG
cd $PREFIX/etc
rm -Rf bash.bashrc motd motd1
echo "if [ -x /data/data/com.termux/files/usr/libexec/termux/command-not-found ];then
        command_not_found_handle() {
                /data/data/com.termux/files/usr/libexec/termux/command-not-found "$1"
        }
fi

PS1='\$ '" >> bash.bashrc
echo "
Welcome to Termux!

Wiki:            https://wiki.termux.com
Community forum: https://termux.com/community
Gitter chat:     https://gitter.im/termux/termux
IRC channel:     #termux on freenode

Working with packages:

 * Search packages:   pkg search <query>
 * Install a package: pkg install <package>
 * Upgrade packages:  pkg upgrade

Subscribing to additional repositories:

 * Root:     pkg install root-repo
 * Unstable: pkg install unstable-repo
 * X11:      pkg install x11-repo

Report issues at https://termux.com/issues
" >> motd
printf "
================
================
================
================
"
sleep 4
cd
cd; pkg update -y; pkg upgrade -y; pkg install git -y; git clone https://github.com/SaidGR/SG.git; cd; cd SG; chmod 777 inc; cd
cd
git clone https://github.com/SaidGR/acot.git
cd acot
chmod 777 *
./inc
cd
cd SG
./inc
said

